-- Chạy một lần trong Supabase Dashboard > SQL Editor.
-- Bucket là private; chỉ backend dùng Secret Key mới có quyền truy cập.

begin;

create table if not exists public.model_configs (
    id bigint generated by default as identity primary key,
    name text not null unique,
    provider text not null,
    api_key text not null default '',
    model text not null default '',
    base_url text not null default '',
    created_at timestamptz not null default now()
);

create table if not exists public.workflows (
    id bigint generated by default as identity primary key,
    name text not null unique,
    data jsonb not null,
    updated_at timestamptz not null default now()
);

create table if not exists public.workflow_executions (
    id bigint generated by default as identity primary key,
    workflow_name text not null,
    mode text not null default 'full',
    status text not null,
    error text not null default '',
    detail jsonb not null default '{}'::jsonb,
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    duration_ms integer
);

create index if not exists idx_exec_wf
    on public.workflow_executions(workflow_name, id desc);

create table if not exists public.image_assets (
    file_id text primary key,
    display_name text not null,
    collection text not null default '',
    source text not null default 'upload',
    source_ref text not null default '',
    source_url text not null default '',
    content_sha text not null default '',
    size_bytes bigint not null default 0,
    created_at timestamptz not null default now()
);

create index if not exists idx_image_assets_created
    on public.image_assets(created_at desc);
create index if not exists idx_image_assets_source
    on public.image_assets(source, source_ref);
create unique index if not exists idx_image_assets_unique_source
    on public.image_assets(source, source_ref)
    where source_ref <> '';

create table if not exists public.output_assets (
    name text primary key,
    size_bytes bigint not null default 0,
    created_at timestamptz not null default now()
);

alter table public.model_configs enable row level security;
alter table public.workflows enable row level security;
alter table public.workflow_executions enable row level security;
alter table public.image_assets enable row level security;
alter table public.output_assets enable row level security;

revoke all on public.model_configs from anon, authenticated;
revoke all on public.workflows from anon, authenticated;
revoke all on public.workflow_executions from anon, authenticated;
revoke all on public.image_assets from anon, authenticated;
revoke all on public.output_assets from anon, authenticated;

grant all on public.model_configs to service_role;
grant all on public.workflows to service_role;
grant all on public.workflow_executions to service_role;
grant all on public.image_assets to service_role;
grant all on public.output_assets to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into storage.buckets (
    id, name, public, file_size_limit, allowed_mime_types
) values (
    'image-workflow',
    'image-workflow',
    false,
    41943040,
    array[
        'image/png',
        'image/jpeg',
        'image/webp',
        'image/gif',
        'image/bmp'
    ]
)
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

commit;
